# Generated by Django 2.1 on 2018-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], default=0, max_length=50, verbose_name='设备状态'),
        ),
    ]
