# Generated by Django 2.1 on 2018-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180808_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='sub_asset_type',
            field=models.CharField(choices=[('1', 'PC服务器'), ('2', '小型机'), ('3', '刀片机')], default=0, max_length=64, verbose_name='服务器类型'),
        ),
    ]
