# Generated by Django 2.1 on 2018-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180808_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='sub_asset_type',
            field=models.CharField(choices=[('1', '路由器'), ('2', '交换机'), ('3', '工业交换机'), ('4', '无线控制器'), ('5', '无线AP')], default=0, max_length=64, verbose_name='网络设备类型'),
        ),
        migrations.AlterField(
            model_name='securitydevice',
            name='sub_asset_type',
            field=models.CharField(choices=[('1', '防火墙'), ('2', '入侵检测设备'), ('3', '入侵防御设备'), ('4', '综合安全网关'), ('5', '数据库审计系统'), ('6', '运维审计系统'), ('7', '防病毒网关'), ('8', 'WAF防火墙'), ('9', '安全配置核查'), ('10', '网络准入系统'), ('11', '网闸设备'), ('12', 'VPN设备')], default=0, max_length=64, verbose_name='安全设备类型'),
        ),
        migrations.AlterField(
            model_name='software',
            name='sub_asset_type',
            field=models.CharField(choices=[('1', '操作系统'), ('2', '数据库'), ('3', '中间件')], default=0, max_length=64, verbose_name='软件类型'),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='sub_asset_type',
            field=models.CharField(choices=[('1', '磁盘阵列'), ('2', '网络存储器'), ('3', '光纤交换机'), ('4', '磁带库'), ('5', '磁带机')], default=0, max_length=64, verbose_name='存储设备类型'),
        ),
    ]
