# Generated by Django 2.1 on 2018-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180808_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('1', '硬件变更'), ('2', '新增配件'), ('3', '设备下线'), ('4', '设备上线'), ('5', '定期维护'), ('6', '业务上线\\更新\\变更'), ('7', '其它')], default=4, max_length=64, verbose_name='事件类型'),
        ),
    ]
